<<<<<<< HEAD
// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/23/2025, 11:34:42 AM
=======
// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/23/2025, 11:25:04 AM
>>>>>>> 4951cd50ec4973bb68d902c6b632ffcb722c5f34
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/neiro/Documents/propject/freelance/Pobedonantigra/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/neiro/Documents/propject/freelance/Pobedonantigra/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/neiro/Documents/propject/freelance/Pobedonantigra/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/neiro/Documents/propject/freelance/Pobedonantigra/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/neiro/Documents/propject/freelance/Pobedonantigra/plugins/**/*.{js,ts,mjs}","C:/Users/neiro/Documents/propject/freelance/Pobedonantigra/composables/**/*.{js,ts,mjs}","C:/Users/neiro/Documents/propject/freelance/Pobedonantigra/utils/**/*.{js,ts,mjs}","C:/Users/neiro/Documents/propject/freelance/Pobedonantigra/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/neiro/Documents/propject/freelance/Pobedonantigra/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/neiro/Documents/propject/freelance/Pobedonantigra/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/neiro/Documents/propject/freelance/Pobedonantigra/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;